/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.popup;

import Util.laundry_management_connection;
import com.barcodelib.barcode.Linear;
import java.io.File;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import tools.dialogControl;
import tools.queryControl;
import tools.tableControl;
import tools.tableControl.TableUpdateMode;

/**
 *
 * @author Rynare
 */
public class lihatPenjualan extends java.awt.Dialog {

    /**
     * Creates new form lihatPenjualan1
     */
    
    //koneksi
    laundry_management_connection koneksi = new laundry_management_connection();
    ResultSet rs;
    ResultSetMetaData rsmd;

    String barcode_destination_folder = "src/barcode/";

    tableControl tableControl = new tableControl();

    //variabel
    int id_penjualan = 1;

public void showBarcode(String file_source_path) {
        File imageFile = new File(file_source_path);
        if (imageFile.exists()) {
            ImageIcon imgThisImg = new ImageIcon(file_source_path);
            if (imgThisImg.getIconHeight() > 0) {
                barcode_label.setIcon(imgThisImg);
                barcode_label.setText("");
            } else {
                // Handle the case when the image cannot be loaded
                System.out.println("Failed to load the image");
            }
        } else {
            // Handle the case when the image file does not exist
            System.out.println("Image file does not exist");
        }
    }

    enum BarcodeFileExtension {
        PNG
    }

    public String createBarcode(String destination_folder, String barcode_filename, BarcodeFileExtension file_extension) {
        try {
            Linear barcode = new Linear();
            barcode.setType(Linear.CODE128);
            barcode.setData(barcode_filename);
            barcode.setI(11.0f);
            barcode.renderBarcode(destination_folder + barcode_filename + "." + file_extension.toString().toLowerCase());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Cetak Barcode: " + e.getMessage());
        }
        return destination_folder + barcode_filename + "." + file_extension.toString().toLowerCase();
    }

    public int getIdPenjualan() {
        return this.id_penjualan;
    }

    public void setIdPenjualan(int ID) {
        this.id_penjualan = ID;
    }

    public void loadDataPelanggan() {
        id_penjualan_field.setText(Integer.toString(getIdPenjualan()));
        try {
            rs = koneksi.getDataWithPreparedStatement("CALL GetDataPelangganFromPenjualan(?)", getIdPenjualan());
            while (rs.next()) {
                nama_pelanggan_field.setText(rs.getString("nama_pelanggan"));
                alamat_field.setText(rs.getString("alamat"));
                no_telp_field.setText(rs.getString("no_telp"));
                catatan_text_area.setText(rs.getString("catatan"));
            }
        } catch (SQLException e) {

        } finally {
            koneksi.closeConnection();
        }
    }

    public void loadTableLayananPenjualan() {
        tableControl.loadTableFromDB(tabel_daftar_layanan, TableUpdateMode.ALWAYS_UPDATE, "CALL GetLayananDataFromPenjualan(?)", getIdPenjualan());
    }

    public void loadAllData() {
        loadDataPelanggan();
        loadTableLayananPenjualan();
    }


    
    public lihatPenjualan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        barcode_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id_penjualan_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        alamat_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        no_telp_field = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nama_pelanggan_field = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_daftar_layanan = new javax.swing.JTable();
        kButton2 = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatan_text_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        auto_print_check = new javax.swing.JCheckBox();

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        kGradientPanel1.setBackground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel1.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel1.setkTransparentControls(false);

        barcode_label.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        barcode_label.setForeground(new java.awt.Color(255, 255, 255));
        barcode_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barcode_label.setText("Klik Untuk Menampilkan Barcode");
        barcode_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barcode_labelMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Penjualan");

        id_penjualan_field.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pelanggan");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alamat");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NO Telp");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton3.setText("Update");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Pelanggan");

        nama_pelanggan_field.setEditable(false);

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton5.setText("Update");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(id_penjualan_field))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama_pelanggan_field)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(no_telp_field, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(alamat_field))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_penjualan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nama_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton5))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(no_telp_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(15, 15, 15))
        );

        tabel_daftar_layanan.setAutoCreateRowSorter(true);
        tabel_daftar_layanan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabel_daftar_layanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabel_daftar_layanan.setToolTipText("");
        tabel_daftar_layanan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel_daftar_layanan.setGridColor(new java.awt.Color(102, 102, 102));
        tabel_daftar_layanan.setRowHeight(24);
        jScrollPane1.setViewportView(tabel_daftar_layanan);

        kButton2.setText("Cetak Nota");
        kButton2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton2.setkAllowGradient(false);
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 0));
        kButton2.setkHoverColor(new java.awt.Color(188, 204, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton2MouseClicked(evt);
            }
        });

        catatan_text_area.setColumns(20);
        catatan_text_area.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catatan_text_area.setLineWrap(true);
        catatan_text_area.setRows(5);
        jScrollPane2.setViewportView(catatan_text_area);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Catatan : ");

        kButton3.setText("Simpan");
        kButton3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton3.setkAllowGradient(false);
        kButton3.setkBackGroundColor(new java.awt.Color(0, 153, 153));
        kButton3.setkEndColor(new java.awt.Color(231, 64, 51));
        kButton3.setkHoverColor(new java.awt.Color(0, 139, 153));
        kButton3.setkHoverEndColor(new java.awt.Color(231, 64, 51));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(231, 64, 51));
        kButton3.setkIndicatorColor(new java.awt.Color(231, 64, 51));
        kButton3.setkSelectedColor(new java.awt.Color(231, 64, 51));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daftar Layanan : ");

        auto_print_check.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        auto_print_check.setForeground(new java.awt.Color(255, 255, 255));
        auto_print_check.setText("Auto Print");
        auto_print_check.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barcode_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(auto_print_check))
                                    .addComponent(kButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(20, 20, 20))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barcode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(auto_print_check))
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        barcode_label.setText("Klik Untuk Menampilkan Barcode");
        barcode_label.setIcon(null);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void barcode_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barcode_labelMouseClicked
        // TODO add your handling code here:
        String barcode_filename = id_penjualan_field.getText();
        String result = createBarcode(barcode_destination_folder, barcode_filename, BarcodeFileExtension.PNG);
        showBarcode(result);
        System.out.println(result);
    }//GEN-LAST:event_barcode_labelMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int id_pelanggan;
        String no_telp = no_telp_field.getText();

        try {
            String query = "SELECT penjualan.id_pelanggan FROM penjualan WHERE id_penjualan = " + id_penjualan_field.getText();
            ResultSet rs = koneksi.getData(query);

            if (rs.next()) {
                id_pelanggan = rs.getInt("id_pelanggan");

                String updateQuery = "UPDATE pelanggan SET no_telp = ? WHERE id_pelanggan = ?";
                Object[] value = {no_telp, id_pelanggan};
                queryControl.updateData(koneksi, updateQuery, value);
            }
        } catch (SQLException e) {
            // Handle the exception appropriately
            e.printStackTrace();
        } finally {
            koneksi.closeConnection();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String nomer_hp;
        int id_penjualan = Integer.valueOf(id_penjualan_field.getText());
        try {
            String query = "select pelanggan.no_telp from pelanggan inner join penjualan on penjualan.id_pelanggan = pelanggan.id_pelanggan where penjualan.id_penjualan = " + id_penjualan;
            ResultSet rs = koneksi.getData(query);
            if (rs.next()) {
                nomer_hp = rs.getString("no_telp");
                no_telp_field.setText(nomer_hp);
            }
        } catch (Exception e) {
        } finally {
            koneksi.closeConnection();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        int id_pelanggan;
        String alamat = alamat_field.getText();

        try {
            String query = "SELECT penjualan.id_pelanggan FROM penjualan WHERE id_penjualan = ?";
            ResultSet rs = koneksi.getDataWithPreparedStatement(query, id_penjualan_field.getText());

            if (rs.next()) {
                id_pelanggan = rs.getInt("id_pelanggan");

                String updateQuery = "UPDATE pelanggan SET alamat = ? WHERE id_pelanggan = ?";
                Object[] value = {alamat, id_pelanggan};
                queryControl.updateData(koneksi, updateQuery, value);
            }
        } catch (SQLException e) {
            dialogControl.SQLFailedShow(this, e);
        } finally {
            koneksi.closeConnection();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void kButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton2MouseClicked
        // TODO add your handling code here:
        this.setAlwaysOnTop(false);
        JasperPrint jasperPrint;
        try {
            String report = "C:\\this is college\\S2\\Workshop Pemrogaman Aplikasi\\laundry\\src\\report\\Nota.jrxml";
            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("id_penjualan", id_penjualan_field.getText());

            JasperReport compiled_report = JasperCompileManager.compileReport(report);
            jasperPrint = JasperFillManager.fillReport(compiled_report, parameters, koneksi.getConnection());
            if (auto_print_check.isSelected()) {
                JasperPrintManager.printReport(jasperPrint, false);
            } else {
                JasperPrintManager.printReport(jasperPrint, true);
            }
        } catch (JRException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_kButton2MouseClicked

    private void kButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton3MouseClicked
        // TODO add your handling code here:
        int id_penjualan = Integer.valueOf(id_penjualan_field.getText());
        String catatan = catatan_text_area.getText();
        String query = "Update penjualan set penjualan.catatan = ? Where penjualan.id_penjualan = ?";
        Object[] value = {catatan, id_penjualan};
        queryControl.updateData(koneksi, query, value);
    }//GEN-LAST:event_kButton3MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadAllData();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lihatPenjualan dialog = new lihatPenjualan(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_field;
    private javax.swing.JCheckBox auto_print_check;
    private javax.swing.JLabel barcode_label;
    private javax.swing.JTextArea catatan_text_area;
    private javax.swing.JTextField id_penjualan_field;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField nama_pelanggan_field;
    private javax.swing.JTextField no_telp_field;
    private javax.swing.JTable tabel_daftar_layanan;
    // End of variables declaration//GEN-END:variables
}
