/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.popup;

import Util.laundry_management_connection;
import java.awt.Frame;
import java.sql.ResultSet;
import java.sql.SQLException;
import tools.dialogControl;


/**
 *
 * @author Rynare
 */
public class lupaSandiPertanyaan extends java.awt.Dialog {

    /**
     * Creates new form lupaSandiPertanyaan1
     */
    
    laundry_management_connection koneksi = new laundry_management_connection();
    ResultSet rs;

    public String Username;
    int id_laundry;
    int id_pertanyaan;
    Frame frameParent;
    
    lupaSandiUbahSandi lupaSandiUbahSandi = new lupaSandiUbahSandi(frameParent,true);

    public void checkAnswer() {
        String pertanyaan = pertanyaan_field.getText();
        String jawaban = jawaban_field.getText();
        if (!(pertanyaan.isEmpty() || jawaban.isEmpty())) {
            try {
                String query = "CALL CekPertanyaanDanJawaban(?, ?)";
                rs = koneksi.getDataWithPreparedStatement(query, id_pertanyaan, jawaban);
                if (rs.next()) {
                    if (rs.getString("Result").equals("benar")) {
                        if (!lupaSandiUbahSandi.isVisible()) {
                            lupaSandiUbahSandi.id_laundry = id_laundry;
                            lupaSandiUbahSandi.setVisible(true);
                        }
                        this.dispose();
                    } else if (rs.getString("Result").equals("salah")) {
                        dialogControl.showWarningMessage(this, "Jawaban yang anda berikan SALAH!!!");
                    }
                }
            } catch (SQLException e) {
                dialogControl.SQLFailedShow(this, e);
            } finally {
                koneksi.closeConnection();
            }
        } else {
            dialogControl.showWarningMessage(this, "Harap Isi JAWABAN anda!!!");
        }
    }
    
    public lupaSandiPertanyaan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        frameParent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pertanyaan_field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jawaban_field = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Pertanyaan");

        pertanyaan_field.setEditable(false);

        jLabel8.setText("Jawaban");

        jawaban_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jawaban_fieldActionPerformed(evt);
            }
        });

        kButton1.setBorder(null);
        kButton1.setText("Lanjutkan...");
        kButton1.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(232, Short.MAX_VALUE)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pertanyaan_field)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jawaban_field))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pertanyaan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jawaban_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jawaban_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jawaban_fieldActionPerformed
        // TODO add your handling code here:
        checkAnswer();
    }//GEN-LAST:event_jawaban_fieldActionPerformed

    private void kButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseClicked
        // TODO add your handling code here:
        checkAnswer();
    }//GEN-LAST:event_kButton1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            System.out.println("" + Username);
            ResultSet rsGetId = koneksi.getDataWithPreparedStatement("SELECT id_laundry from laundry WHERE username = ?", Username);
            if (rsGetId.next()) {
                this.id_laundry = rsGetId.getInt("id_laundry");
                String query = "SELECT * FROM lupa_sandi WHERE id_laundry = ?";
                ResultSet rsGetQ = koneksi.getDataWithPreparedStatement(query, this.id_laundry);
                if (rsGetQ.next()) {
                    id_pertanyaan = rsGetQ.getInt("id_pertanyaan");
                    pertanyaan_field.setText(rsGetQ.getString("pertanyaan"));
                }
            }
        } catch (SQLException e) {
            dialogControl.SQLFailedShow(this, e);
            this.dispose();
        } finally {
            koneksi.closeConnection();
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lupaSandiPertanyaan dialog = new lupaSandiPertanyaan(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jawaban_field;
    private com.k33ptoo.components.KButton kButton1;
    private javax.swing.JTextField pertanyaan_field;
    // End of variables declaration//GEN-END:variables
}
