/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.popup;

import Util.laundry_management_connection;
import javax.swing.JTable;
import laundry.frames.MainContent;
import tools.dialogControl;
import tools.fieldControl;
import tools.queryControl;
import tools.tableControl;
import tools.tools;

/**
 *
 * @author Rynare
 */
public class Pembayaran extends java.awt.Dialog {

    /**
     * Creates new form NewDialog
     */
    laundry_management_connection koneksi = new laundry_management_connection();
    MainContent parent;

    static int id_penjualan;
    private JTable table;
    private int rowTabel;

    public void setData(int id, int harga) {
        id_penjualan = id;
        total_harga_field.setText(tools.currencyFormatter(Integer.toString(harga)).format());
    }

    public void setTable(JTable table, int row) {
        this.table = table;
        rowTabel = row;
    }

    public void setParent(MainContent parent) {
        this.parent = parent;
    }

    public void showFrame() {
        this.setVisible(true);
    }

    public Pembayaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        kembalian_field = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tunai_field = new javax.swing.JTextField();
        total_harga_field = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        kButton5 = new com.k33ptoo.components.KButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        kembalian_field.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total Harga");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Tunai");

        tunai_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tunai_fieldKeyReleased(evt);
            }
        });

        total_harga_field.setEditable(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Kembalian");

        kButton5.setText("Tandai Selesai / Sudah Bayar");
        kButton5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton5.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton5.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(total_harga_field))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tunai_field)
                            .addComponent(kembalian_field, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_harga_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunai_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        tunai_field.setText("");
        kembalian_field.setText("");
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tunai_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunai_fieldKeyReleased
        // TODO add your handling code here:
        tunai_field.setText(fieldControl.onlyNumber(tunai_field));
        String total_harga_formated = tools.currencyFormatter(tunai_field.getText()).format();
        tunai_field.setText(total_harga_formated);
        if (!total_harga_field.getText().isEmpty()) {
            if (!tunai_field.getText().isEmpty()) {
                int tunai_value = Integer.parseInt(tools.currencyFormatter(tunai_field.getText()).unformat());
                int total_harga = Integer.parseInt(tools.currencyFormatter(total_harga_field.getText()).unformat());
                String hasil = Integer.toString(tunai_value - total_harga);
                kembalian_field.setText(tools.currencyFormatter(hasil).format());
            } else {
                int total_harga = Integer.parseInt(tools.currencyFormatter(total_harga_field.getText()).unformat());
                total_harga = total_harga - total_harga * 2;
                kembalian_field.setText(tools.currencyFormatter(Integer.toString(total_harga)).format());
            }
        }
    }//GEN-LAST:event_tunai_fieldKeyReleased

    private void kButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton5MouseClicked
        // TODO add your handling code here:
        String total_harga = total_harga_field.getText();
        String tunai = tunai_field.getText();
        String kembalian = kembalian_field.getText();

        if (!(total_harga.isEmpty() || tunai.isEmpty() || kembalian.isEmpty()) && id_penjualan >= 0) {
            int tunai_int = Integer.parseInt(tools.currencyFormatter(tunai_field.getText()).unformat());
            int total_harga_int = Integer.parseInt(tools.currencyFormatter(total_harga_field.getText()).unformat());
            int hasil_int = tunai_int - total_harga_int;
            if (hasil_int >= 0) {
                String query = "UPDATE penjualan SET status = 'selesai' WHERE id_penjualan = ?";
                boolean isUpdate = queryControl.updateData(koneksi, query, id_penjualan);
                if (isUpdate) {
                    total_harga_field.setText("");
                    tunai_field.setText("");
                    kembalian_field.setText("");
                    dialogControl.showSuccessMessage(this, "Kembalian Rp." + kembalian);
                    this.dispose();
                    parent.setEnabled(true);
                    tableControl.deleteTableRow(table, rowTabel);
                }
            } else {
                dialogControl.showWarningMessage(this, "Uang yang anda bayarkan kurang Rp." + tools.currencyFormatter(Integer.toString(total_harga_int - tunai_int)).format());
            }
        } else {
            dialogControl.showWarningMessage(this, "Harap isi semua kolom!!!");
        }
    }//GEN-LAST:event_kButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pembayaran dialog = new Pembayaran(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel2;
    private com.k33ptoo.components.KButton kButton5;
    private javax.swing.JTextField kembalian_field;
    private static javax.swing.JTextField total_harga_field;
    private javax.swing.JTextField tunai_field;
    // End of variables declaration//GEN-END:variables
}
