/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.popup;

import Util.laundry_management_connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JComboBox;
import tools.tableControl;
import tools.tableControl.TableUpdateMode;

/**
 *
 * @author Rynare
 */
public class tambahPenjualanSelectPelanggan extends java.awt.Dialog {

    /**
     * Creates new form tambahPenjualanSelectPelanggan1
     */
    int prevRow = -1;
    int clickCount = 0;
    laundry_management_connection koneksiDB = new laundry_management_connection();
    ResultSet rs;
    ResultSetMetaData rsmd;

    tableControl tableControl = new tableControl();
    /**
     * Creates new form tambahPenjualanSelectLayanan
     */
    public String getComboboxValue(JComboBox combobox) {
        Object selectedValue = combobox.getSelectedItem();
        String selectedItemString = selectedValue.toString();
        return selectedItemString;
    }

    public void loadTableFromFilter() {
        String query = "SELECT * FROM searchPelanggan";
        String userInput = SearchBarPelanggan.getText();
        String tipeKondisi = getComboboxValue(comboBoxPelanggan);
        String kondisi = "";

        if (!userInput.isEmpty()) {
            if (tipeKondisi.equals("Nomer Telpon")) {
                kondisi += " WHERE searchPelanggan.`Nomer Telpon` = " + userInput;
            } else if (tipeKondisi.equals("Nama_Pelanggan")) {
                kondisi += " WHERE searchPelanggan.`Nama` LIKE '%" + userInput + "%'";
            }else if (tipeKondisi.equals("Alamat")){
                kondisi += " WHERE searchPelanggan.`Alamat` LIKE '%" + userInput + "%'";
            }

            try {
                ResultSet resultSet = koneksiDB.getData(query + kondisi);
                loadTablePelanggan(query + kondisi, TableUpdateMode.ALWAYS_UPDATE);
                resultSet.close();
            } catch (SQLException ex) {
                System.out.println("Gagal menjalankan query: " + ex.getMessage());
            } finally {
                koneksiDB.closeConnection();
            }
        }else{
            tableControl.loadTableFromDB(tabelPelanggan, TableUpdateMode.ALWAYS_UPDATE, "SELECT * FROM searchPelanggan");
        }
    }

// =============================================================================
// =============================/ Loader Method /===============================
// =============================================================================

    public void loadTablePelanggan(String query, TableUpdateMode mode, Object... values) {
        tableControl.loadTableFromDB(tabelPelanggan, mode, query, values);
    }

    public void submitToTambahPenjualan(int id, String nama_pelanggan, String alamat, String no_telp) {
        tambahPenjualan.setPelanggan(id, nama_pelanggan, alamat,no_telp);
    }

    
    
    
    public tambahPenjualanSelectPelanggan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        SearchBarPelanggan = new javax.swing.JTextField();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        jSeparator1 = new javax.swing.JSeparator();
        comboBoxPelanggan = new javax.swing.JComboBox<>();
        kButton7 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelanggan);

        kGradientPanel1.setBackground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkBorderRadius(20);
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 102, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));

        SearchBarPelanggan.setBackground(new java.awt.Color(102, 102, 102));
        SearchBarPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchBarPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        SearchBarPelanggan.setBorder(null);
        SearchBarPelanggan.setCaretColor(new java.awt.Color(255, 255, 255));
        SearchBarPelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SearchBarPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarPelangganActionPerformed(evt);
            }
        });

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24px/icons8_search_24px.png"))); // NOI18N
        rSPanelImage3.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        comboBoxPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        comboBoxPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama_Pelanggan", "Alamat", "Nomer Telpon" }));
        comboBoxPelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxPelangganItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchBarPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(comboBoxPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBarPelanggan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelImage3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxPelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        kButton7.setText("Refresh Table\n");
        kButton7.setActionCommand("");
        kButton7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton7.setkEndColor(new java.awt.Color(24, 144, 255));
        kButton7.setkHoverEndColor(new java.awt.Color(24, 144, 255));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton7.setkStartColor(new java.awt.Color(24, 144, 255));
        kButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton7MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("* klik 2 kali pada pelanggan untuk memilih");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        clickCount++;
        if (clickCount == 2) {
            if (prevRow == tabelPelanggan.getSelectedRow()) {
                int baris = tabelPelanggan.getSelectedRow();
                System.out.println("Double-clicked on row: " + prevRow);
                int id = (int) tabelPelanggan.getValueAt(baris, 0);
                String nama_pelanggan = (String) tabelPelanggan.getValueAt(baris, 1);
                String alamat = (String) tabelPelanggan.getValueAt(baris, 2);
                String no_telp = (String) tabelPelanggan.getValueAt(baris, 3);
                submitToTambahPenjualan(id, nama_pelanggan, alamat, no_telp);
                this.dispose();
            }
            clickCount = 0;
        } else {
            prevRow = tabelPelanggan.getSelectedRow();
            Timer timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    clickCount = 0;
                }
            }, 500); // Waktu dalam milidetik untuk mereset clickCount jika tidak ada double-click berikutnya dalam 200ms
        }
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void SearchBarPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarPelangganActionPerformed
        // TODO add your handling code here:
        loadTableFromFilter();
    }//GEN-LAST:event_SearchBarPelangganActionPerformed

    private void comboBoxPelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxPelangganItemStateChanged
        // TODO add your handling code here:
        loadTableFromFilter();
    }//GEN-LAST:event_comboBoxPelangganItemStateChanged

    private void kButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton7MouseClicked
        // TODO add your handling code here:
        loadTablePelanggan("SELECT * FROM searchPelanggan", TableUpdateMode.ALWAYS_UPDATE);
    }//GEN-LAST:event_kButton7MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadTablePelanggan("SELECT * FROM searchPelanggan", TableUpdateMode.ALWAYS_UPDATE);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambahPenjualanSelectPelanggan dialog = new tambahPenjualanSelectPelanggan(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SearchBarPelanggan;
    private javax.swing.JComboBox<String> comboBoxPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private rojerusan.RSPanelImage rSPanelImage3;
    private javax.swing.JTable tabelPelanggan;
    // End of variables declaration//GEN-END:variables
}
