/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.pages;

import Util.laundry_management_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import laundry.frames.MainContent;
import tools.comboBoxControl;
import tools.dialogControl;
import tools.queryControl;
import tools.tableControl;
import tools.tableControl.TableUpdateMode;

/**
 *
 * @author Rynare
 */
public class Parfum extends javax.swing.JPanel {

    /**
     * Creates new form parfum
     */
    laundry_management_connection koneksiDB = new laundry_management_connection();
    tableControl tableControl = new tableControl();
    
    private int id_laundry;
    private MainContent parent;
    private ResultSet rs ;

    public void setParent(MainContent parent) {
        this.parent = parent;
    }

    public void setID(int id_laundry) {
        this.id_laundry = id_laundry;
    }
    
    public void render(TableUpdateMode mode){
        loadTableStok("Select * from searchBarang", mode);
    }
    
    public Parfum() {
        initComponents();
        disableTrash();
    }

    public void disableTrash() {
        kGradientPanel15.setVisible(false);
        jLabel35.setVisible(false);
        insert_banyak_stok_field.setVisible(false);
    }
    
    public void loadTableParfumFromFilter() {
        String query = "SELECT * FROM searchBarang";
        String userInput = searchBarParfum.getText();
        String tipeKondisi = comboBoxControl.getComboBoxValue(parfumComboBoxFilter);
        String kondisi = "";

        if (!userInput.isEmpty()) {
            switch (tipeKondisi) {
                case "Habis":
                    kondisi += " WHERE searchBarang.status = 'habis'";
                    break;
                case "Tersedia":
                    kondisi += " WHERE searchBarang.status = 'tersedia'";
                    break;
                case "Nama Parfum":
                    kondisi += " WHERE searchBarang.`Nama Barang` LIKE '%" + userInput + "%'";
                    break;
                default:
                    break;
            }

            try {
                rs = koneksiDB.getData(query + kondisi);
                loadTableStok(query + kondisi, TableUpdateMode.ALWAYS_UPDATE);
            } catch (SQLException ex) {
                System.out.println("Gagal menjalankan query: " + ex.getMessage());
            } finally {
                koneksiDB.closeConnection();
            }
        } else {
            tableControl.loadTableFromDB(tabelParfum, TableUpdateMode.ALWAYS_UPDATE, "SELECT * FROM searchBarang");
        }
    }
    
    

    public void loadTableStok(String query, tableControl.TableUpdateMode mode, Object... value) {
        tableControl.loadTableFromDB(tabelParfum, mode, query, value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel12 = new com.k33ptoo.components.KGradientPanel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        insert_nama_barang_field = new javax.swing.JTextField();
        insert_banyak_stok_field = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        kButton20 = new com.k33ptoo.components.KButton();
        jLabel44 = new javax.swing.JLabel();
        ParfumStatusComboBox = new javax.swing.JComboBox<>();
        kGradientPanel13 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelParfum = new javax.swing.JTable();
        kGradientPanel11 = new com.k33ptoo.components.KGradientPanel();
        kButton18 = new com.k33ptoo.components.KButton();
        jPanel6 = new javax.swing.JPanel();
        searchBarParfum = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        parfumComboBoxFilter = new javax.swing.JComboBox<>();
        rSPanelImage9 = new rojerusan.RSPanelImage();
        kGradientPanel19 = new com.k33ptoo.components.KGradientPanel();
        jLabel24 = new javax.swing.JLabel();
        kGradientPanel17 = new com.k33ptoo.components.KGradientPanel();
        jLabel23 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        kGradientPanel15 = new com.k33ptoo.components.KGradientPanel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        ID_barang_field = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        nama_barang_field = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        stok_barang_field = new javax.swing.JTextField();
        kButton26 = new com.k33ptoo.components.KButton();
        tambah_stok_warning_text = new javax.swing.JLabel();

        setOpaque(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        kGradientPanel12.setBackground(new java.awt.Color(102, 102, 102));
        kGradientPanel12.setkBorderRadius(20);
        kGradientPanel12.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel12.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel12.setOpaque(false);

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Tambah Parfum");

        jLabel33.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Nama Barang");

        jLabel35.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Banyak Stok ");

        kButton20.setBorder(null);
        kButton20.setText("Tambah Barang");
        kButton20.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton20.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton20.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton20.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton20MouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Status");

        ParfumStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Habis" }));

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator13)
                    .addGroup(kGradientPanel12Layout.createSequentialGroup()
                        .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35)
                            .addComponent(jLabel44))
                        .addGap(16, 16, 16)
                        .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insert_banyak_stok_field)
                            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                                .addComponent(insert_nama_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ParfumStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        kGradientPanel12Layout.setVerticalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_nama_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(5, 5, 5)
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_banyak_stok_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(5, 5, 5)
                .addGroup(kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ParfumStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addGap(9, 9, 9)
                .addComponent(kButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel13.setBackground(new java.awt.Color(102, 102, 102));
        kGradientPanel13.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel13.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel13.setOpaque(false);

        tabelParfum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelParfum.setRowHeight(24);
        tabelParfum.setShowHorizontalLines(false);
        tabelParfum.setShowVerticalLines(false);
        tabelParfum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelParfumMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelParfum);

        kGradientPanel11.setBackground(new java.awt.Color(51, 51, 51));
        kGradientPanel11.setkBorderRadius(20);
        kGradientPanel11.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel11.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel11.setOpaque(false);

        kButton18.setBorder(null);
        kButton18.setText("Cari");
        kButton18.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton18.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton18.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton18.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton18MouseClicked(evt);
            }
        });
        kButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton18ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(30, 39, 66));

        searchBarParfum.setBackground(new java.awt.Color(30, 39, 66));
        searchBarParfum.setForeground(new java.awt.Color(255, 255, 255));
        searchBarParfum.setBorder(null);
        searchBarParfum.setOpaque(false);
        searchBarParfum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarParfumActionPerformed(evt);
            }
        });

        parfumComboBoxFilter.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        parfumComboBoxFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Parfum", "Tersedia", "Habis" }));
        parfumComboBoxFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                parfumComboBoxFilterItemStateChanged(evt);
            }
        });

        rSPanelImage9.setImagen(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24px/icons8_search_24px.png"))); // NOI18N
        rSPanelImage9.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout rSPanelImage9Layout = new javax.swing.GroupLayout(rSPanelImage9);
        rSPanelImage9.setLayout(rSPanelImage9Layout);
        rSPanelImage9Layout.setHorizontalGroup(
            rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        rSPanelImage9Layout.setVerticalGroup(
            rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(rSPanelImage9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBarParfum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parfumComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBarParfum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSPanelImage9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parfumComboBoxFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel19.setkBorderRadius(20);
        kGradientPanel19.setkEndColor(new java.awt.Color(0, 153, 229));
        kGradientPanel19.setkStartColor(new java.awt.Color(0, 153, 229));
        kGradientPanel19.setOpaque(false);
        kGradientPanel19.setPreferredSize(new java.awt.Dimension(40, 40));
        kGradientPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel19MouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(231, 64, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24pxNew/icons8_refresh_30px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel19Layout = new javax.swing.GroupLayout(kGradientPanel19);
        kGradientPanel19.setLayout(kGradientPanel19Layout);
        kGradientPanel19Layout.setHorizontalGroup(
            kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel19Layout.setVerticalGroup(
            kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        kGradientPanel17.setkBorderRadius(20);
        kGradientPanel17.setkEndColor(new java.awt.Color(231, 64, 51));
        kGradientPanel17.setkStartColor(new java.awt.Color(231, 64, 51));
        kGradientPanel17.setOpaque(false);
        kGradientPanel17.setPreferredSize(new java.awt.Dimension(30, 30));
        kGradientPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel17MouseClicked(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(231, 64, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24pxNew/icons8_Trash_Can_24px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel17Layout = new javax.swing.GroupLayout(kGradientPanel17);
        kGradientPanel17.setLayout(kGradientPanel17Layout);
        kGradientPanel17Layout.setHorizontalGroup(
            kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel17Layout.setVerticalGroup(
            kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kButton3.setBorder(null);
        kButton3.setText("Habis / Tersedia");
        kButton3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton3.setkAllowGradient(false);
        kButton3.setkBackGroundColor(new java.awt.Color(204, 204, 0));
        kButton3.setkBorderRadius(20);
        kButton3.setkHoverColor(new java.awt.Color(219, 219, 0));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkPressedColor(new java.awt.Color(204, 204, 0));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel11Layout = new javax.swing.GroupLayout(kGradientPanel11);
        kGradientPanel11.setLayout(kGradientPanel11Layout);
        kGradientPanel11Layout.setHorizontalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel11Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel11Layout.setVerticalGroup(
            kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(kGradientPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
        kGradientPanel13.setLayout(kGradientPanel13Layout);
        kGradientPanel13Layout.setHorizontalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel13Layout.setVerticalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel13Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kGradientPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        kGradientPanel15.setBackground(new java.awt.Color(102, 102, 102));
        kGradientPanel15.setkBorderRadius(20);
        kGradientPanel15.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel15.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel15.setOpaque(false);

        jLabel40.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Tambah Stok");

        ID_barang_field.setEditable(false);

        jLabel41.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("ID Barang");

        jLabel42.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Nama Barang");

        jLabel43.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Stok /pcs");

        kButton26.setBorder(null);
        kButton26.setText("Tambah Stok");
        kButton26.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton26.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton26.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton26.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        tambah_stok_warning_text.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        tambah_stok_warning_text.setForeground(new java.awt.Color(255, 0, 0));
        tambah_stok_warning_text.setText("* Klik barang yang berada di tabel daftar barang dahulu jika ingin menambah stok");

        javax.swing.GroupLayout kGradientPanel15Layout = new javax.swing.GroupLayout(kGradientPanel15);
        kGradientPanel15.setLayout(kGradientPanel15Layout);
        kGradientPanel15Layout.setHorizontalGroup(
            kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator17)
                    .addGroup(kGradientPanel15Layout.createSequentialGroup()
                        .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41))
                        .addGap(28, 28, 28)
                        .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_barang_field)
                            .addComponent(stok_barang_field)))
                    .addComponent(tambah_stok_warning_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel15Layout.setVerticalGroup(
            kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah_stok_warning_text)
                .addGap(10, 10, 10)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_barang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(10, 10, 10)
                .addComponent(kButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kGradientPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(kGradientPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kGradientPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(kGradientPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton20MouseClicked
        // TODO add your handling code here:
        String id_barang = "";
        String nama_barang = insert_nama_barang_field.getText();
        //        String stok_barang = insert_banyak_stok_field.getText();
        if (!nama_barang.isEmpty()) {
            String status = ParfumStatusComboBox.getSelectedItem().toString().toLowerCase();

            try {
                String getIdBarangQuery = "SELECT ID FROM searchbarang ORDER BY ID DESC LIMIT 1;";
                ResultSet resultSet = koneksiDB.getData(getIdBarangQuery);
                if (resultSet.next()) {
                    id_barang = Integer.toString(Integer.parseInt(resultSet.getString("ID")) + 1);
                    String query = "INSERT INTO barang (id_barang, nama_barang, status) VALUES (?, ?, ?)";
                    Object[] value = {id_barang, nama_barang, status};
                    boolean isInserted = queryControl.insertData(koneksiDB, query, value);
                    if (isInserted) {
                        insert_nama_barang_field.setText("");
                        dialogControl.showSuccessMessage(parent, "Data Parfum BERHASIL ditambahkan.");
                    }
                }
            } catch (SQLException ex) {
                dialogControl.SQLFailedInsert(parent, ex);
            } finally {
                koneksiDB.closeConnection();
            }
        } else {
            dialogControl.showWarningMessage(parent, "Harap masukkan Nama Parfum!!!");
        }
    }//GEN-LAST:event_kButton20MouseClicked

    private void tabelParfumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelParfumMouseClicked
        // TODO add your handling code here:
        if (tambah_stok_warning_text.isVisible()) {
            tambah_stok_warning_text.setVisible(false);
        }
        int row = tabelParfum.rowAtPoint(evt.getPoint());

        String id_barang_value = tabelParfum.getValueAt(row, 0).toString();
        String nama_barang_value = tabelParfum.getValueAt(row, 1).toString();

        ID_barang_field.setText(id_barang_value);
        nama_barang_field.setText(nama_barang_value);
    }//GEN-LAST:event_tabelParfumMouseClicked

    private void kButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton18MouseClicked
        // TODO add your handling code here:
        loadTableParfumFromFilter();
    }//GEN-LAST:event_kButton18MouseClicked

    private void kButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton18ActionPerformed

    private void searchBarParfumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarParfumActionPerformed
        // TODO add your handling code here:
        loadTableParfumFromFilter();
    }//GEN-LAST:event_searchBarParfumActionPerformed

    private void parfumComboBoxFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_parfumComboBoxFilterItemStateChanged
        // TODO add your handling code here:
        loadTableParfumFromFilter();
    }//GEN-LAST:event_parfumComboBoxFilterItemStateChanged

    private void kGradientPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel19MouseClicked
        // TODO add your handling code here:
        loadTableStok("Select * from searchBarang", TableUpdateMode.ALWAYS_UPDATE);
    }//GEN-LAST:event_kGradientPanel19MouseClicked

    private void kGradientPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel17MouseClicked
        // TODO add your handling code here:
        int baris = tabelParfum.getSelectedRow();
        if (baris >= 0) {
            int id_barang = Integer.parseInt(tabelParfum.getValueAt(baris, 0).toString());
            String parfum = tabelParfum.getValueAt(baris, 1).toString();
            int option = dialogControl.showWarningOption(parent, "Konfirmasi", "Yakin ingin menghapus " + parfum);
            if (option == JOptionPane.YES_OPTION) {
                String query = "DELETE FROM barang WHERE id_barang = ?";
                boolean isDelete = queryControl.deleteData(koneksiDB, query, id_barang);
                if (isDelete) {
                    tableControl.deleteTableRow(tabelParfum,baris);
                    dialogControl.showSuccessMessage(parent, "Data Parfum berhasil di hapus");
                }
            }
        } else {
            dialogControl.showWarningMessage(parent, "Harap pilih kolom pada tabel!!!");
        }
    }//GEN-LAST:event_kGradientPanel17MouseClicked

    private void kButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton3MouseClicked
        // TODO add your handling code here:
        int baris = tabelParfum.getSelectedRow();
        if (baris >= 0) {
            int id_parfum = Integer.valueOf(tabelParfum.getValueAt(baris, 0).toString());
            String nama_parfum = tabelParfum.getValueAt(baris, 1).toString();
            String status = tabelParfum.getValueAt(baris, 2).toString();
            if (status.equals("habis")) {
                int option = dialogControl.showQuestionOption(parent, "Konfirmasi", "Ingin mengubah status " + nama_parfum + " Menjadi \"Tersedia\"?");
                if (option == JOptionPane.YES_OPTION) {
                    String query = "UPDATE barang SET barang.status = 'tersedia' WHERE id_barang = ?";
                    boolean isUpdate = queryControl.updateData(koneksiDB, query, id_parfum);
                    if (isUpdate) {
                        tabelParfum.setValueAt("tersedia", baris, 2);
                    }
                }
            } else if (status.equals("tersedia")) {
                int option = dialogControl.showWarningOption(parent, "Konfirmasi", "Ingin mengubah status " + nama_parfum + "Menjadi \"Habis\"?");
                if (option == JOptionPane.YES_OPTION) {
                    String query = "UPDATE barang SET barang.status = 'habis' WHERE id_barang = ?";
                    boolean isUpdate = queryControl.updateData(koneksiDB, query, id_parfum);
                    if (isUpdate) {
                        tabelParfum.setValueAt("habis", baris, 2);
                    }
                }
            }

        } else {
            dialogControl.showWarningMessage(parent, "Harap pilih baris yang ingin dihapus pada tabel!!!");
        }
    }//GEN-LAST:event_kButton3MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_barang_field;
    private javax.swing.JComboBox<String> ParfumStatusComboBox;
    private javax.swing.JTextField insert_banyak_stok_field;
    private javax.swing.JTextField insert_nama_barang_field;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator17;
    private com.k33ptoo.components.KButton kButton18;
    private com.k33ptoo.components.KButton kButton20;
    private com.k33ptoo.components.KButton kButton26;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel11;
    private com.k33ptoo.components.KGradientPanel kGradientPanel12;
    private com.k33ptoo.components.KGradientPanel kGradientPanel13;
    private com.k33ptoo.components.KGradientPanel kGradientPanel15;
    private com.k33ptoo.components.KGradientPanel kGradientPanel17;
    private com.k33ptoo.components.KGradientPanel kGradientPanel19;
    private javax.swing.JTextField nama_barang_field;
    private javax.swing.JComboBox<String> parfumComboBoxFilter;
    private rojerusan.RSPanelImage rSPanelImage9;
    private javax.swing.JTextField searchBarParfum;
    private javax.swing.JTextField stok_barang_field;
    private javax.swing.JTable tabelParfum;
    private javax.swing.JLabel tambah_stok_warning_text;
    // End of variables declaration//GEN-END:variables
}
