/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.pages;

import Util.laundry_management_connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import laundry.frames.MainContent;
import tools.browser;
import tools.comboBoxControl;
import tools.dialogControl;
import tools.fieldControl;
import tools.queryControl;
import tools.tableControl;
import tools.tableControl.TableUpdateMode;

/**
 *
 * @author Rynare
 */
public class Pelanggan extends javax.swing.JPanel {

    /**
     * Creates new form pelanggan
     */
    laundry_management_connection koneksiDB = new laundry_management_connection();
    tableControl tableControl = new tableControl();
    
    private int id_laundry;
    private MainContent parent;
    private ResultSet rs ;

    public void setParent(MainContent parent) {
        this.parent = parent;
    }

    public void setID(int id_laundry) {
        this.id_laundry = id_laundry;
    }
    
    public void render(TableUpdateMode mode){
        loadTablePelanggan("Select * from searchPelanggan", mode);
    }
    
    public Pelanggan() {
        initComponents();
    }
    
    public void loadTablePelangganFromFilter() {
        String query = "SELECT * FROM searchPelanggan";
        String userInput = searchBar_pelanggan.getText();
        String tipeKondisi = comboBoxControl.getComboBoxValue(comboBoxPelanggan);
        String kondisi = "";

        if (!userInput.isEmpty()) {
            System.out.println(tipeKondisi);
            switch (tipeKondisi) {
                case "Nomer Telpon":
                    kondisi += " WHERE searchPelanggan.`Nomer Telpon` = " + userInput;
                    break;
                case "Nama Pelanggan":
                    kondisi += " WHERE searchPelanggan.`Nama` LIKE '%" + userInput + "%'";
                    break;
                case "Alamat":
                    kondisi += " WHERE searchPelanggan.`Alamat` LIKE '%" + userInput + "%'";
                    break;
                default:
                    break;
            }

            try {
                rs = koneksiDB.getData(query + kondisi);
                loadTablePelanggan(query + kondisi, TableUpdateMode.ALWAYS_UPDATE);
                System.out.println("kondisi : " + kondisi);
            } catch (SQLException ex) {
                System.out.println("Gagal menjalankan query: " + ex.getMessage());
            } finally {
                koneksiDB.closeConnection();
            }
        } else {
            tableControl.loadTableFromDB(tabelPelanggan, TableUpdateMode.ALWAYS_UPDATE, "SELECT * FROM searchPelanggan");
        }
    }
    
    public void loadTablePelanggan(String query, tableControl.TableUpdateMode mode, Object... value) {
        tableControl.loadTableFromDB(tabelPelanggan, mode, query, value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel7 = new com.k33ptoo.components.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        Id_pelanggan_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nama_pelanggan_field = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        no_telpon_pelanggan_field = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        kButton11 = new com.k33ptoo.components.KButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        alamat_pelanggan_field = new javax.swing.JTextArea();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kButton4 = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        rSPanelImage4 = new rojerusan.RSPanelImage();
        searchBar_pelanggan = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        comboBoxPelanggan = new javax.swing.JComboBox<>();
        kButton15 = new com.k33ptoo.components.KButton();
        kGradientPanel23 = new com.k33ptoo.components.KGradientPanel();
        jLabel32 = new javax.swing.JLabel();
        kGradientPanel16 = new com.k33ptoo.components.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        insert_nama_pelanggan_field = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        insert_no_telpon_pelanggan_field = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        kButton14 = new com.k33ptoo.components.KButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        insert_alamat_pelanggan_field = new javax.swing.JTextArea();

        setOpaque(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        kGradientPanel7.setBackground(new java.awt.Color(30, 39, 66));
        kGradientPanel7.setkBorderRadius(20);
        kGradientPanel7.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel7.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel7.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ubah Data Pelanggan");

        Id_pelanggan_field.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ID Pelanggan");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama Pelanggan");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No Telpon");

        no_telpon_pelanggan_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_telpon_pelanggan_fieldKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alamat");

        kButton11.setBorder(null);
        kButton11.setText("Simpan");
        kButton11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton11.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton11.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton11MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24pxNew/icons8_whatsapp_24px.png"))); // NOI18N
        jButton2.setText("Chat!");
        jButton2.setToolTipText("Buka WhatsApp Web");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        alamat_pelanggan_field.setColumns(20);
        alamat_pelanggan_field.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alamat_pelanggan_field.setLineWrap(true);
        alamat_pelanggan_field.setTabSize(0);
        alamat_pelanggan_field.setWrapStyleWord(true);
        jScrollPane5.setViewportView(alamat_pelanggan_field);

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Id_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel7Layout.createSequentialGroup()
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel7Layout.createSequentialGroup()
                                .addComponent(no_telpon_pelanggan_field)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nama_pelanggan_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                    .addComponent(kButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel7Layout.createSequentialGroup()
                        .addComponent(Id_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_telpon_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel19))
                            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))))
                    .addComponent(jLabel16))
                .addGap(11, 11, 11)
                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        kGradientPanel3.setBackground(new java.awt.Color(30, 39, 66));
        kGradientPanel3.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel3.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel3.setOpaque(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        tabelPelanggan.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelPelanggan.setOpaque(false);
        tabelPelanggan.setRowHeight(24);
        tabelPelanggan.setShowHorizontalLines(false);
        tabelPelanggan.setShowVerticalLines(false);
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        kGradientPanel2.setBackground(new java.awt.Color(30, 39, 66));
        kGradientPanel2.setkBorderRadius(20);
        kGradientPanel2.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel2.setkStartColor(new java.awt.Color(30, 39, 66));

        kButton4.setBorder(null);
        kButton4.setText("Cari Pelanggan");
        kButton4.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton4.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton4MouseClicked(evt);
            }
        });
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 39, 66));

        rSPanelImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24px/icons8_search_24px.png"))); // NOI18N
        rSPanelImage4.setPreferredSize(new java.awt.Dimension(24, 24));

        javax.swing.GroupLayout rSPanelImage4Layout = new javax.swing.GroupLayout(rSPanelImage4);
        rSPanelImage4.setLayout(rSPanelImage4Layout);
        rSPanelImage4Layout.setHorizontalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        rSPanelImage4Layout.setVerticalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        searchBar_pelanggan.setBackground(new java.awt.Color(30, 39, 66));
        searchBar_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        searchBar_pelanggan.setBorder(null);
        searchBar_pelanggan.setOpaque(false);
        searchBar_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBar_pelangganActionPerformed(evt);
            }
        });

        comboBoxPelanggan.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        comboBoxPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Pelanggan", "Nomer Telpon", "Alamat" }));
        comboBoxPelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxPelangganItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rSPanelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar_pelanggan))
                    .addComponent(jSeparator4))
                .addGap(10, 10, 10)
                .addComponent(comboBoxPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rSPanelImage4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBar_pelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        kButton15.setBorder(null);
        kButton15.setText("Hapus Data");
        kButton15.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton15.setkEndColor(new java.awt.Color(231, 64, 51));
        kButton15.setkHoverEndColor(new java.awt.Color(231, 64, 51));
        kButton15.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton15.setkHoverStartColor(new java.awt.Color(231, 64, 51));
        kButton15.setkStartColor(new java.awt.Color(231, 64, 51));
        kButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton15MouseClicked(evt);
            }
        });

        kGradientPanel23.setToolTipText("Refresh Table");
        kGradientPanel23.setkBorderRadius(20);
        kGradientPanel23.setkEndColor(new java.awt.Color(0, 153, 229));
        kGradientPanel23.setkStartColor(new java.awt.Color(0, 153, 229));
        kGradientPanel23.setOpaque(false);
        kGradientPanel23.setPreferredSize(new java.awt.Dimension(40, 40));
        kGradientPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel23MouseClicked(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(231, 64, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24pxNew/icons8_refresh_30px.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel23Layout = new javax.swing.GroupLayout(kGradientPanel23);
        kGradientPanel23.setLayout(kGradientPanel23Layout);
        kGradientPanel23Layout.setHorizontalGroup(
            kGradientPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel23Layout.setVerticalGroup(
            kGradientPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kGradientPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(kButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        kGradientPanel16.setBackground(new java.awt.Color(30, 39, 66));
        kGradientPanel16.setkBorderRadius(20);
        kGradientPanel16.setkEndColor(new java.awt.Color(30, 39, 66));
        kGradientPanel16.setkStartColor(new java.awt.Color(30, 39, 66));
        kGradientPanel16.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tambah Pelanggan");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Pelanggan");

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No Telpon");

        insert_no_telpon_pelanggan_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                insert_no_telpon_pelanggan_fieldKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Alamat");

        kButton14.setBorder(null);
        kButton14.setText("Tambahkan Pelanggan");
        kButton14.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        kButton14.setkEndColor(new java.awt.Color(0, 153, 153));
        kButton14.setkHoverEndColor(new java.awt.Color(0, 153, 153));
        kButton14.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton14.setOpaque(false);
        kButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton14MouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/24pxNew/icons8_whatsapp_24px.png"))); // NOI18N
        jButton1.setText("Chat!");
        jButton1.setToolTipText("Buka WhatsApp Web");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        insert_alamat_pelanggan_field.setColumns(20);
        insert_alamat_pelanggan_field.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        insert_alamat_pelanggan_field.setLineWrap(true);
        insert_alamat_pelanggan_field.setTabSize(0);
        insert_alamat_pelanggan_field.setWrapStyleWord(true);
        jScrollPane4.setViewportView(insert_alamat_pelanggan_field);

        javax.swing.GroupLayout kGradientPanel16Layout = new javax.swing.GroupLayout(kGradientPanel16);
        kGradientPanel16.setLayout(kGradientPanel16Layout);
        kGradientPanel16Layout.setHorizontalGroup(
            kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(16, 16, 16)
                        .addComponent(insert_nama_pelanggan_field))
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(49, 49, 49)
                        .addComponent(insert_no_telpon_pelanggan_field)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane4))
                    .addComponent(kButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel16Layout.setVerticalGroup(
            kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_nama_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel21))
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_no_telpon_pelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(kButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kGradientPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kGradientPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void no_telpon_pelanggan_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_telpon_pelanggan_fieldKeyReleased
        // TODO add your handling code here:
        no_telpon_pelanggan_field.setText(fieldControl.onlyNumber(no_telpon_pelanggan_field));
    }//GEN-LAST:event_no_telpon_pelanggan_fieldKeyReleased

    private void kButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton11MouseClicked
        // TODO add your handling code here:
        int baris = tabelPelanggan.getSelectedRow();
        int id = (int) tabelPelanggan.getValueAt(baris, 0);
        String nama_pelanggan = nama_pelanggan_field.getText();
        String no_telpon = no_telpon_pelanggan_field.getText();
        String alamat = alamat_pelanggan_field.getText();

        if (!(nama_pelanggan.isEmpty() || no_telpon.isEmpty() || alamat.isEmpty())) {
            String query = "UPDATE FROM layanan WHERE layanan.id_layanan = ?";
            boolean isUpdate = queryControl.updateData(koneksiDB, query, id);
            if (isUpdate) {
                dialogControl.showSuccessMessage(parent, "Data Berhasil diperbarui.");
            }
        } else {
            dialogControl.showWarningMessage(parent, "Harap isi semua kolom!!!");
        }
    }//GEN-LAST:event_kButton11MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String no_hp = no_telpon_pelanggan_field.getText();
        if (!no_hp.isEmpty()) {
            browser.openWhatsappWeb(no_hp, "Hallo");
        } else {
            dialogControl.showWarningMessage(parent, "Harap isi NOMER HP Pelanggan!");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        // TODO add your handling code here:
        int row = tabelPelanggan.rowAtPoint(evt.getPoint());

        String id_pelanggan_value = tabelPelanggan.getValueAt(row, 0).toString();
        String nama_pelanggan_value = tabelPelanggan.getValueAt(row, 1).toString();
        String no_telpon_value = tabelPelanggan.getValueAt(row, 2).toString();
        String alamat_value = tabelPelanggan.getValueAt(row, 3).toString();

        Id_pelanggan_field.setText(id_pelanggan_value);
        nama_pelanggan_field.setText(nama_pelanggan_value);
        no_telpon_pelanggan_field.setText(no_telpon_value);
        alamat_pelanggan_field.setText(alamat_value);
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void kButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton4MouseClicked
        // TODO add your handling code here:
        loadTablePelangganFromFilter();
    }//GEN-LAST:event_kButton4MouseClicked

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void searchBar_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBar_pelangganActionPerformed
        // TODO add your handling code here:
        loadTablePelangganFromFilter();
    }//GEN-LAST:event_searchBar_pelangganActionPerformed

    private void comboBoxPelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxPelangganItemStateChanged
        // TODO add your handling code here:
        loadTablePelangganFromFilter();
    }//GEN-LAST:event_comboBoxPelangganItemStateChanged

    private void kButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton15MouseClicked
        // TODO add your handling code here:
        int baris = tabelPelanggan.getSelectedRow();
        if (baris >= 0) {
            String nama = tabelPelanggan.getValueAt(baris, 1).toString();
            int option = dialogControl.showWarningOption(parent, "Konfirmasi", "Yakin ingin menghapus \"" + nama + "\"");
            if (option == JOptionPane.YES_OPTION) {
                int id = (int) tabelPelanggan.getValueAt(baris, 0);
                String query = "DELETE FROM pelanggan WHERE pelanggan.id_pelanggan = ?";
                boolean isDeleted = queryControl.deleteData(koneksiDB, query, id);
                if (isDeleted) {
                    tableControl.deleteTableRow(tabelPelanggan,baris);
                    Id_pelanggan_field.setText("");
                    nama_pelanggan_field.setText("");
                    no_telpon_pelanggan_field.setText("");
                    alamat_pelanggan_field.setText("");
                }
            }
        } else {
            dialogControl.showWarningMessage(parent, "Harap pilih kolom yang ingin dihapus");
        }

    }//GEN-LAST:event_kButton15MouseClicked

    private void kGradientPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel23MouseClicked
        // TODO add your handling code here:
        loadTablePelanggan("Select * from searchPelanggan", TableUpdateMode.ALWAYS_UPDATE);
    }//GEN-LAST:event_kGradientPanel23MouseClicked

    private void insert_no_telpon_pelanggan_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insert_no_telpon_pelanggan_fieldKeyReleased
        // TODO add your handling code here:
        insert_no_telpon_pelanggan_field.setText(fieldControl.onlyNumber(insert_no_telpon_pelanggan_field));
    }//GEN-LAST:event_insert_no_telpon_pelanggan_fieldKeyReleased

    private void kButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton14MouseClicked
        // TODO add your handling code here:
        String id_pelanggan = "";
        String nama_pelanggan = insert_nama_pelanggan_field.getText();
        String no_telpon = insert_no_telpon_pelanggan_field.getText();
        String alamat = insert_alamat_pelanggan_field.getText();

        if (!(nama_pelanggan.isEmpty() || no_telpon.isEmpty() || alamat.isEmpty())) {
            try {
                String getIdPelangganQuery = "SELECT ID FROM searchpelanggan ORDER BY ID DESC LIMIT 1";
                ResultSet resultSet = koneksiDB.getData(getIdPelangganQuery);
                if (resultSet.next()) {
                    id_pelanggan = Integer.toString(Integer.parseInt(resultSet.getString("ID")) + 1);
                    String queryInsertPelanggan = "INSERT INTO pelanggan (id_pelanggan, nama_pelanggan, no_telp, alamat) VALUES (?, ?, ?, ?)";
                    Object[] valueInsertPelanggan = {id_pelanggan, nama_pelanggan, no_telpon, alamat};
                    boolean isInsert = queryControl.insertData(koneksiDB, queryInsertPelanggan, valueInsertPelanggan);
                    if (isInsert) {
                        dialogControl.showSuccessMessage(parent, "Data Pelanggan berhasil ditambah.");
                        insert_nama_pelanggan_field.setText("");
                        insert_no_telpon_pelanggan_field.setText("");
                        insert_alamat_pelanggan_field.setText("");
                    }
                }
            } catch (SQLException ex) {
                dialogControl.SQLFailedShow(parent, ex);
            } finally {
                koneksiDB.closeConnection();
            }
        } else {
            dialogControl.showWarningMessage(parent, "Harap isi semua kolom!!!");
        }
    }//GEN-LAST:event_kButton14MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String no_hp = insert_no_telpon_pelanggan_field.getText();
        if (!no_hp.isEmpty()) {
            browser.openWhatsappWeb(no_hp, "Hallo");
        } else {
            dialogControl.showWarningMessage(parent, "Harap isi NOMER HP Pelanggan!");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_pelanggan_field;
    private javax.swing.JTextArea alamat_pelanggan_field;
    private javax.swing.JComboBox<String> comboBoxPelanggan;
    private javax.swing.JTextArea insert_alamat_pelanggan_field;
    private javax.swing.JTextField insert_nama_pelanggan_field;
    private javax.swing.JTextField insert_no_telpon_pelanggan_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton14;
    private com.k33ptoo.components.KButton kButton15;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel16;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel23;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel7;
    private javax.swing.JTextField nama_pelanggan_field;
    private javax.swing.JTextField no_telpon_pelanggan_field;
    private rojerusan.RSPanelImage rSPanelImage4;
    private javax.swing.JTextField searchBar_pelanggan;
    private javax.swing.JTable tabelPelanggan;
    // End of variables declaration//GEN-END:variables
}
