package laundry.frames;

import Util.laundry_management_connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import laundry.popup.Pertanyaan;
import laundry.popup.lupaSandiPertanyaan;
import tools.dialogControl;
import tools.tools.TimeUtil;

public class LoginForm extends javax.swing.JFrame {

    // koneksi 
    laundry_management_connection koneksi = new laundry_management_connection();
    ResultSet rs;

    // frame
    Pertanyaan pertanyaan = new Pertanyaan(this,true);
    lupaSandiPertanyaan lupaSandiPertanyaan = new lupaSandiPertanyaan(this,true);

    public LoginForm() {
        initComponents();
        closeAllPanel();
        demoCheck.setVisible(false);
    }

    public static void setUsernameSigninValue(String t) {
        signIn_user_field.setText(t);
    }

    public void setUsernameSignin(String username) {
        signIn_user_field.setText(username);
    }

    public void openPanel(JPanel panel) {
        closeAllPanel();
        if (!panel.isVisible()) {
            panel.setVisible(true);
        }
    }

    public void closeAllPanel() {
        SignInForm.setVisible(false);
        SignUpForm.setVisible(false);
    }

    public void login(String username, String password) {
        if (!(username.isEmpty() || password.isEmpty())) {
            String query = "CALL Login(?, ?)";
            Object[] value = {username, password};
            int id_laundry = 0;
            try {
                rs = koneksi.getDataWithPreparedStatement(query, value);

                if (rs.next()) {
                    String result = rs.getString("Result");
                    if (result.equals("berhasil")) {
                        rs = koneksi.getDataWithPreparedStatement("SELECT id_laundry FROM laundry WHERE username = ?", username);
                        if (rs.next()) {
                            id_laundry = rs.getInt("id_laundry");
                            MainContent laundry = new laundry.frames.MainContent();
                            laundry.setData(id_laundry);
                            laundry.prepare();
                            laundry.setVisible(true);
                            this.setVisible(false);
                        }
                    } else if (result.equals("gagal")) {
                        dialogControl.showWarningMessage(this, "USERNAME atau PASSWORD yang anda masukkan salah!!!");
                    }
                }
            } catch (SQLException e) {
                // dialogControl.SQLFailedShow(this, e);
                e.getSQLState();
            } finally {
                koneksi.closeConnection();
            }

        } else {
            dialogControl.showWarningMessage(this, "Harap Isi Semua Kolom!!!");
        }
    }

    public void openSignIn() {
        SignUpForm.setVisible(false);
        SignInForm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        LoginFormContainer = new javax.swing.JPanel();
        SignInForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Daftar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signIn_user_field = new javax.swing.JTextField();
        signIn_pass_field = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel7 = new javax.swing.JLabel();
        show_pass_check = new javax.swing.JCheckBox();
        SignUpForm = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        InputDaftarUsername = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        InputDaftarTelp = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jLabel40 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        InputDaftarNamaLaundry = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        InputDaftarPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputDaftarAlamat = new javax.swing.JTextArea();
        InputDaftarReType1 = new javax.swing.JTextField();
        demoCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Laundry Management");
        setName("LoginFrame"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        SideBackground.setBackground(new java.awt.Color(13, 52, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/loginBG.png"))); // NOI18N

        waktu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setText("16 : 00");
        waktu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tanggal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal.setText("Kamis, 04 September 2003");
        tanggal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        LoginFormContainer.setLayout(new java.awt.CardLayout());

        SignInForm.setBackground(new java.awt.Color(19, 70, 106));
        SignInForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignInForm.setName("LoginForm"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tidak Punya Akun?");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MASUK");

        Daftar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Daftar.setForeground(new java.awt.Color(12, 140, 233));
        Daftar.setText("Daftar");
        Daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaftarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        signIn_user_field.setBackground(new java.awt.Color(19, 70, 106));
        signIn_user_field.setForeground(new java.awt.Color(255, 255, 255));
        signIn_user_field.setBorder(null);
        signIn_user_field.setCaretColor(new java.awt.Color(255, 255, 255));
        signIn_user_field.setOpaque(false);

        signIn_pass_field.setBackground(new java.awt.Color(19, 70, 106));
        signIn_pass_field.setForeground(new java.awt.Color(255, 255, 255));
        signIn_pass_field.setBorder(null);
        signIn_pass_field.setCaretColor(new java.awt.Color(255, 255, 255));
        signIn_pass_field.setOpaque(false);
        signIn_pass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_pass_fieldActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle1.setText("Masuk");
        rSMaterialButtonRectangle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 140, 233));
        jLabel7.setText("Lupa Password?");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        show_pass_check.setForeground(new java.awt.Color(255, 255, 255));
        show_pass_check.setText("Show Password");
        show_pass_check.setOpaque(false);
        show_pass_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pass_checkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignInFormLayout = new javax.swing.GroupLayout(SignInForm);
        SignInForm.setLayout(SignInFormLayout);
        SignInFormLayout.setHorizontalGroup(
            SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInFormLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(SignInFormLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Daftar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show_pass_check)
                            .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(signIn_user_field)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(signIn_pass_field)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        SignInFormLayout.setVerticalGroup(
            SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInFormLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignInFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Daftar))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signIn_user_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signIn_pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_pass_check)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        LoginFormContainer.add(SignInForm, "card2");

        SignUpForm.setBackground(new java.awt.Color(19, 70, 106));
        SignUpForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpForm.setName("LoginForm"); // NOI18N

        jLabel32.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel32.setText("Sudah Punya Akun?");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel32.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel33.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Daftar");

        jLabel34.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(12, 140, 233));
        jLabel34.setText("Masuk");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Username");

        InputDaftarUsername.setBackground(new java.awt.Color(19, 70, 106));
        InputDaftarUsername.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarUsername.setForeground(new java.awt.Color(255, 255, 255));
        InputDaftarUsername.setBorder(null);
        InputDaftarUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        InputDaftarUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDaftarUsernameActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Alamat");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("No Telpon");

        InputDaftarTelp.setBackground(new java.awt.Color(19, 70, 106));
        InputDaftarTelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarTelp.setForeground(new java.awt.Color(255, 255, 255));
        InputDaftarTelp.setBorder(null);
        InputDaftarTelp.setCaretColor(new java.awt.Color(255, 255, 255));
        InputDaftarTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDaftarTelpActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Pin");

        rSMaterialButtonRectangle2.setText("Daftar");
        rSMaterialButtonRectangle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle2MouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Masukkan Ulang Pin");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nama Laundry");

        InputDaftarNamaLaundry.setBackground(new java.awt.Color(19, 70, 106));
        InputDaftarNamaLaundry.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarNamaLaundry.setForeground(new java.awt.Color(255, 255, 255));
        InputDaftarNamaLaundry.setBorder(null);
        InputDaftarNamaLaundry.setCaretColor(new java.awt.Color(255, 255, 255));
        InputDaftarNamaLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDaftarNamaLaundryActionPerformed(evt);
            }
        });

        InputDaftarPassword.setBackground(new java.awt.Color(19, 70, 106));
        InputDaftarPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarPassword.setForeground(new java.awt.Color(255, 255, 255));
        InputDaftarPassword.setBorder(null);
        InputDaftarPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        InputDaftarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDaftarPasswordActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        InputDaftarAlamat.setColumns(20);
        InputDaftarAlamat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarAlamat.setLineWrap(true);
        InputDaftarAlamat.setRows(5);
        InputDaftarAlamat.setWrapStyleWord(true);
        InputDaftarAlamat.setBorder(null);
        InputDaftarAlamat.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(InputDaftarAlamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        InputDaftarReType1.setBackground(new java.awt.Color(19, 70, 106));
        InputDaftarReType1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        InputDaftarReType1.setForeground(new java.awt.Color(255, 255, 255));
        InputDaftarReType1.setBorder(null);
        InputDaftarReType1.setCaretColor(new java.awt.Color(255, 255, 255));
        InputDaftarReType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDaftarReType1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpFormLayout = new javax.swing.GroupLayout(SignUpForm);
        SignUpForm.setLayout(SignUpFormLayout);
        SignUpFormLayout.setHorizontalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel39)
                    .addComponent(InputDaftarTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel33)
                    .addComponent(InputDaftarUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jLabel35)
                    .addGroup(SignUpFormLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator7)
                    .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addComponent(jSeparator8)
                    .addComponent(jLabel36)
                    .addComponent(InputDaftarNamaLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(InputDaftarPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputDaftarReType1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        SignUpFormLayout.setVerticalGroup(
            SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpFormLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignUpFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputDaftarUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputDaftarNamaLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGap(3, 3, 3)
                .addComponent(InputDaftarTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel39)
                .addGap(8, 8, 8)
                .addComponent(InputDaftarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputDaftarReType1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        LoginFormContainer.add(SignUpForm, "card2");

        demoCheck.setForeground(new java.awt.Color(255, 255, 255));
        demoCheck.setText("Mode Demo");
        demoCheck.setOpaque(false);
        demoCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                demoCheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideBackgroundLayout = new javax.swing.GroupLayout(SideBackground);
        SideBackground.setLayout(SideBackgroundLayout);
        SideBackgroundLayout.setHorizontalGroup(
            SideBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBackgroundLayout.createSequentialGroup()
                .addGroup(SideBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SideBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SideBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SideBackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(demoCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(LoginFormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SideBackgroundLayout.setVerticalGroup(
            SideBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginFormContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SideBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(demoCheck)
                .addGap(52, 52, 52)
                .addComponent(waktu)
                .addGap(1, 1, 1)
                .addComponent(tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarMouseClicked
        // TODO add your handling code here:
        try {
            String query = "SELECT COUNT(laundry.id_laundry) from laundry";
            rs = koneksi.getData(query);
            if (rs.next() && !demoCheck.isSelected()) {
                dialogControl.showWarningMessage(this, "Anda sudah pernah mendaftar");
            } else {
                openPanel(SignUpForm);
            }
        } catch (SQLException e) {
            dialogControl.SQLFailedShow(this, e);
        } finally {
            koneksi.closeConnection();
        }
    }//GEN-LAST:event_DaftarMouseClicked

    private void signIn_pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_pass_fieldActionPerformed
        // TODO add your handling code here:
        String username = signIn_user_field.getText();
        String password = new String(signIn_pass_field.getPassword());
        login(username, password);
    }//GEN-LAST:event_signIn_pass_fieldActionPerformed

    private void rSMaterialButtonRectangle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1MouseClicked
        // TODO add your handling code here:
        String username = signIn_user_field.getText();
        String password = new String(signIn_pass_field.getPassword());
        login(username, password);
    }//GEN-LAST:event_rSMaterialButtonRectangle1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                waktu.setText(TimeUtil.realTimeUpdate());
            }
        });
        timer.start();
        tanggal.setText(TimeUtil.realDateUpdate());
    }//GEN-LAST:event_formComponentShown

    private void rSMaterialButtonRectangle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2MouseClicked
        // TODO add your handling code here:
        String username = InputDaftarUsername.getText();
        String nama_laundry = InputDaftarNamaLaundry.getText();
        String alamat = InputDaftarAlamat.getText();
        String no_telp = InputDaftarTelp.getText();
        String password = InputDaftarPassword.getText();
        String re_type_pass = InputDaftarPassword.getText();

        if (!(username.isEmpty() || nama_laundry.isEmpty() || alamat.isEmpty() || no_telp.isEmpty() || password.isEmpty() || re_type_pass.isEmpty())) {
            try {
                rs = koneksi.getDataWithPreparedStatement("SELECT COUNT(username) AS username_count FROM laundry WHERE username = ?", username);
                if (rs.next()) {
                    if (rs.getInt(1) > 0) {
                        int option = dialogControl.showWarningOption(this, "Konfirmasi", "USERNAME Sudah tersedia\nIngin menggunakan USERNAME dari kami?");
                        if (option == JOptionPane.YES_OPTION) {
                            InputDaftarUsername.setText(username + rs.getInt(1));
                        }
                    } else if (rs.getInt(1) == 0) {
                        if (re_type_pass.equals(password)) {
                            String query = "CALL createAccount(?, ?, ?, ?, ?)";
                            Object[] value = {nama_laundry, no_telp, alamat, password, username};
                            pertanyaan.createAccQuery = query;
                            pertanyaan.createAccValue = value;
                            pertanyaan.Username = InputDaftarUsername.getText();
                            pertanyaan.setParent(this);
                            System.out.println("query : " + query);
                            if (!pertanyaan.isVisible()) {
                                pertanyaan.setVisible(true);
                            }
                        } else {
                            dialogControl.showWarningMessage(this, "Password tidak cocok");
                        }
                    }
                }
            } catch (SQLException e) {
                e.getMessage();
            }
        } else {
            dialogControl.showWarningMessage(this, "Harap isi semua data yang diperlukan!!!");
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle2MouseClicked

    private void InputDaftarTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDaftarTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDaftarTelpActionPerformed

    private void InputDaftarUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDaftarUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDaftarUsernameActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        openPanel(SignInForm);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void InputDaftarNamaLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDaftarNamaLaundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDaftarNamaLaundryActionPerformed

    private void InputDaftarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDaftarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDaftarPasswordActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (!signIn_user_field.getText().isEmpty()) {
            if (!lupaSandiPertanyaan.isVisible()) {
                lupaSandiPertanyaan.Username = signIn_user_field.getText();
                lupaSandiPertanyaan.setVisible(true);
            }
        } else {
            dialogControl.showWarningMessage(this, "Harap Masukkan USERNAME Anda!!!");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void InputDaftarReType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDaftarReType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDaftarReType1ActionPerformed

    private void show_pass_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pass_checkMouseClicked
        // TODO add your handling code here:
        if (show_pass_check.isSelected()) {
            signIn_pass_field.setEchoChar((char)0);
        }else{
            signIn_pass_field.setEchoChar('*');
        }
    }//GEN-LAST:event_show_pass_checkMouseClicked

    private void demoCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_demoCheckMouseClicked
        // TODO add your handling code here:
        if (demoCheck.isSelected()) {
            dialogControl.showSuccessMessage(this, "Mode demo aktif. anda dapat membuat banyak akun sekarang");
        }
    }//GEN-LAST:event_demoCheckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Daftar;
    private javax.swing.JTextArea InputDaftarAlamat;
    private javax.swing.JTextField InputDaftarNamaLaundry;
    private javax.swing.JTextField InputDaftarPassword;
    private javax.swing.JTextField InputDaftarReType1;
    private javax.swing.JTextField InputDaftarTelp;
    private javax.swing.JTextField InputDaftarUsername;
    private javax.swing.JPanel LoginFormContainer;
    private javax.swing.JPanel SideBackground;
    private javax.swing.JPanel SignInForm;
    private javax.swing.JPanel SignUpForm;
    private javax.swing.JCheckBox demoCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private javax.swing.JCheckBox show_pass_check;
    private javax.swing.JPasswordField signIn_pass_field;
    private static javax.swing.JTextField signIn_user_field;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
