/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry.frames;

import Util.laundry_management_connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import laundry.popup.*;
import tools.*;
import tools.tableControl.TableUpdateMode;
import tools.tools.TimeUtil;

/**
 *
 * @author snsv
 */
public final class MainContent extends javax.swing.JFrame {

    JPanel activePanel;

    int prevRow = -1;
    int clickCount = 0;
    int prev_riwayat_tahun;
    int prev_riwayat_bulan;
    int id_laundry = -1;

    // koneksi ebject
    laundry_management_connection koneksiDB = new laundry_management_connection();
    ResultSet rs;
    ResultSetMetaData rsmd;

    //support object
    tableControl tableControl = new tableControl();

    // popup object
    profil profil = new profil();

    public void setData(int id_laundry) {
        this.id_laundry = id_laundry;
    }

    public void openPanel(JPanel panel) {
        activePanel = panel;
        if (!panel.isVisible()) {
            closeAllPanel();
            panel.setVisible(true);
        }
    }

    public void closeAllPanel() {
        panel_dashboard.setVisible(false);
        panel_riwayat.setVisible(false);
        panel_pelanggan.setVisible(false);
        panel_layanan.setVisible(false);
        panel_parfum.setVisible(false);
    }

    public MainContent() {
        initComponents();
        closeAllPanel();
    }

    public void prepare() {
        System.out.println("prepare");
        System.out.println("id_laundry : " +this.id_laundry);
        beranda1.setID(this.id_laundry);
        layanan1.setID(this.id_laundry);
        parfum1.setID(this.id_laundry);
        pelanggan1.setID(this.id_laundry);
        riwayat1.setID(this.id_laundry);

        beranda1.setParent(this);
        layanan1.setParent(this);
        parfum1.setParent(this);
        pelanggan1.setParent(this);
        riwayat1.setParent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        nav_dashboard = new com.k33ptoo.components.KButton();
        nav_parfum = new com.k33ptoo.components.KButton();
        nav_layanan = new com.k33ptoo.components.KButton();
        nav_pelanggan = new com.k33ptoo.components.KButton();
        nav_riwayat = new com.k33ptoo.components.KButton();
        jSeparator2 = new javax.swing.JSeparator();
        waktu = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        nav_riwayat1 = new com.k33ptoo.components.KButton();
        mainPanel = new javax.swing.JPanel();
        panel_dashboard = new javax.swing.JPanel();
        beranda1 = new laundry.pages.Beranda();
        panel_pelanggan = new javax.swing.JPanel();
        pelanggan1 = new laundry.pages.Pelanggan();
        panel_layanan = new javax.swing.JPanel();
        layanan1 = new laundry.pages.Layanan();
        panel_parfum = new javax.swing.JPanel();
        parfum1 = new laundry.pages.Parfum();
        panel_riwayat = new javax.swing.JPanel();
        riwayat1 = new laundry.pages.Riwayat();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laundry Management");
        setSize(new java.awt.Dimension(0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        Sidebar.setBackground(new java.awt.Color(30, 39, 66));

        nav_dashboard.setBorder(null);
        nav_dashboard.setForeground(new java.awt.Color(114, 90, 255));
        nav_dashboard.setText("Beranda");
        nav_dashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_dashboard.setHideActionText(true);
        nav_dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_dashboard.setIconTextGap(15);
        nav_dashboard.setkAllowGradient(false);
        nav_dashboard.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_dashboard.setkBorderRadius(20);
        nav_dashboard.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_dashboard.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_dashboard.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_dashboard.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_dashboard.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_dashboard.setOpaque(false);
        nav_dashboard.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nav_dashboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_dashboardMouseClicked(evt);
            }
        });

        nav_parfum.setBorder(null);
        nav_parfum.setForeground(new java.awt.Color(114, 90, 255));
        nav_parfum.setText("Parfum");
        nav_parfum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_parfum.setkAllowGradient(false);
        nav_parfum.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_parfum.setkBorderRadius(20);
        nav_parfum.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_parfum.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_parfum.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_parfum.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_parfum.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_parfum.setOpaque(false);
        nav_parfum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_parfumMouseClicked(evt);
            }
        });

        nav_layanan.setBorder(null);
        nav_layanan.setForeground(new java.awt.Color(114, 90, 255));
        nav_layanan.setText("Layanan");
        nav_layanan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_layanan.setkAllowGradient(false);
        nav_layanan.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_layanan.setkBorderRadius(20);
        nav_layanan.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_layanan.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_layanan.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_layanan.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_layanan.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_layanan.setOpaque(false);
        nav_layanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_layananMouseClicked(evt);
            }
        });

        nav_pelanggan.setBorder(null);
        nav_pelanggan.setForeground(new java.awt.Color(114, 90, 255));
        nav_pelanggan.setText("Pelanggan");
        nav_pelanggan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_pelanggan.setkAllowGradient(false);
        nav_pelanggan.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_pelanggan.setkBorderRadius(20);
        nav_pelanggan.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_pelanggan.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_pelanggan.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_pelanggan.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_pelanggan.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_pelanggan.setOpaque(false);
        nav_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_pelangganMouseClicked(evt);
            }
        });

        nav_riwayat.setBorder(null);
        nav_riwayat.setForeground(new java.awt.Color(114, 90, 255));
        nav_riwayat.setText("Riwayat");
        nav_riwayat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_riwayat.setkAllowGradient(false);
        nav_riwayat.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_riwayat.setkBorderRadius(20);
        nav_riwayat.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_riwayat.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_riwayat.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_riwayat.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_riwayat.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_riwayat.setOpaque(false);
        nav_riwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_riwayatMouseClicked(evt);
            }
        });

        waktu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setText("16:00");

        tanggal.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal.setText("Kamis, 04 September 2003");

        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Log Out");

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/laundry/assets/50px/icons8_logout_50px_1.png"))); // NOI18N
        rSPanelImage1.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        nav_riwayat1.setBorder(null);
        nav_riwayat1.setForeground(new java.awt.Color(114, 90, 255));
        nav_riwayat1.setText("Profil");
        nav_riwayat1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        nav_riwayat1.setkAllowGradient(false);
        nav_riwayat1.setkBackGroundColor(new java.awt.Color(30, 39, 66));
        nav_riwayat1.setkBorderRadius(20);
        nav_riwayat1.setkForeGround(new java.awt.Color(114, 90, 255));
        nav_riwayat1.setkHoverColor(new java.awt.Color(23, 30, 58));
        nav_riwayat1.setkHoverForeGround(new java.awt.Color(114, 90, 255));
        nav_riwayat1.setkIndicatorColor(new java.awt.Color(114, 90, 255));
        nav_riwayat1.setkPressedColor(new java.awt.Color(19, 25, 47));
        nav_riwayat1.setOpaque(false);
        nav_riwayat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_riwayat1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(nav_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav_pelanggan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav_layanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav_parfum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav_riwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(nav_riwayat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(waktu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal)
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nav_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nav_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nav_parfum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nav_riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nav_riwayat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        mainPanel.setBackground(new java.awt.Color(19, 25, 47));
        mainPanel.setLayout(new java.awt.CardLayout());

        panel_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashboard.setOpaque(false);
        panel_dashboard.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_dashboardComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beranda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beranda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(panel_dashboard, "card2");

        panel_pelanggan.setBackground(new java.awt.Color(102, 102, 102));
        panel_pelanggan.setOpaque(false);
        panel_pelanggan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_pelangganComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panel_pelangganLayout = new javax.swing.GroupLayout(panel_pelanggan);
        panel_pelanggan.setLayout(panel_pelangganLayout);
        panel_pelangganLayout.setHorizontalGroup(
            panel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pelangganLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pelanggan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panel_pelangganLayout.setVerticalGroup(
            panel_pelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pelangganLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pelanggan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(panel_pelanggan, "card3");

        panel_layanan.setBackground(new java.awt.Color(102, 102, 102));
        panel_layanan.setOpaque(false);
        panel_layanan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_layananComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panel_layananLayout = new javax.swing.GroupLayout(panel_layanan);
        panel_layanan.setLayout(panel_layananLayout);
        panel_layananLayout.setHorizontalGroup(
            panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_layananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panel_layananLayout.setVerticalGroup(
            panel_layananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_layananLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(layanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(panel_layanan, "card4");

        panel_parfum.setBackground(new java.awt.Color(102, 102, 102));
        panel_parfum.setOpaque(false);
        panel_parfum.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_parfumComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panel_parfumLayout = new javax.swing.GroupLayout(panel_parfum);
        panel_parfum.setLayout(panel_parfumLayout);
        panel_parfumLayout.setHorizontalGroup(
            panel_parfumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_parfumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parfum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        panel_parfumLayout.setVerticalGroup(
            panel_parfumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_parfumLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(parfum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(panel_parfum, "card6");

        panel_riwayat.setBackground(new java.awt.Color(102, 102, 102));
        panel_riwayat.setOpaque(false);
        panel_riwayat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panel_riwayatComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panel_riwayatLayout = new javax.swing.GroupLayout(panel_riwayat);
        panel_riwayat.setLayout(panel_riwayatLayout);
        panel_riwayatLayout.setHorizontalGroup(
            panel_riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_riwayatLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(riwayat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_riwayatLayout.setVerticalGroup(
            panel_riwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_riwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(riwayat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        mainPanel.add(panel_riwayat, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_dashboardMouseClicked
        // TODO add your handling code here:
        openPanel(panel_dashboard);
        beranda1.render(TableUpdateMode.NORMAL);
    }//GEN-LAST:event_nav_dashboardMouseClicked

    private void nav_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_pelangganMouseClicked
        // TODO add your handling code here:closeAllPanel();
        openPanel(panel_pelanggan);
        pelanggan1.render(TableUpdateMode.NORMAL);
    }//GEN-LAST:event_nav_pelangganMouseClicked

    private void nav_layananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_layananMouseClicked
        // TODO add your handling code here:
        openPanel(panel_layanan);
        layanan1.render(TableUpdateMode.NORMAL);
    }//GEN-LAST:event_nav_layananMouseClicked

    private void nav_parfumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_parfumMouseClicked
        // TODO add your handling code here:
        openPanel(panel_parfum);
        parfum1.render(TableUpdateMode.NORMAL);
    }//GEN-LAST:event_nav_parfumMouseClicked

    private void nav_riwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_riwayatMouseClicked
        // TODO add your handling code here:
        openPanel(panel_riwayat);
        riwayat1.render(TableUpdateMode.ALWAYS_UPDATE);
    }//GEN-LAST:event_nav_riwayatMouseClicked

    private void panel_pelangganComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_pelangganComponentShown

    }//GEN-LAST:event_panel_pelangganComponentShown

    private void panel_dashboardComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_dashboardComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_dashboardComponentShown

    private void panel_layananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_layananComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_layananComponentShown

    private void panel_parfumComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_parfumComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_parfumComponentShown

    private void panel_riwayatComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel_riwayatComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_panel_riwayatComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        beranda1.render(TableUpdateMode.NORMAL);
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                waktu.setText(TimeUtil.realTimeUpdate());
            }
        });
        timer.start();
        tanggal.setText(TimeUtil.realDateUpdate());
    }//GEN-LAST:event_formComponentShown

    private void nav_riwayat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_riwayat1MouseClicked
        // TODO add your handling code here:
        if (!profil.isVisible()) {
            profil.setData(id_laundry);
            profil.setVisible(true);
        }
    }//GEN-LAST:event_nav_riwayat1MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        int option = dialogControl.showWarningOption(this, "Konfirmasi", "Apakah anda yakin ingin keluar?");
        if (option == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new laundry.frames.LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MainContent mainContent = new MainContent();

                if (mainContent.id_laundry < 0) {
                    mainContent.setVisible(false);
                    LoginForm login = new LoginForm();
                    login.setVisible(true);
                } else {
                    mainContent.setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sidebar;
    private laundry.pages.Beranda beranda1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private laundry.pages.Layanan layanan1;
    private javax.swing.JPanel mainPanel;
    private com.k33ptoo.components.KButton nav_dashboard;
    private com.k33ptoo.components.KButton nav_layanan;
    private com.k33ptoo.components.KButton nav_parfum;
    private com.k33ptoo.components.KButton nav_pelanggan;
    private com.k33ptoo.components.KButton nav_riwayat;
    private com.k33ptoo.components.KButton nav_riwayat1;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_layanan;
    private javax.swing.JPanel panel_parfum;
    private javax.swing.JPanel panel_pelanggan;
    private javax.swing.JPanel panel_riwayat;
    private laundry.pages.Parfum parfum1;
    private laundry.pages.Pelanggan pelanggan1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private laundry.pages.Riwayat riwayat1;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
